local addonName, ns = ...

ns.Defaults = {
    version = 7,
    welcomeShown = false,
    enabled = true,
    minQuality = 1,
    showItems = true,
    showMoney = false,
    showVendorValue = false,
    showQuantity = true,
    showOwnedCount = false,
    showIcons = true,
    showBackground = true,
    backgroundOpacity = 0.2,
    backgroundRounded = false,
    rowOpacity = 1.0,
    mouseInteraction = false,
    direction = "UP",
    staticMode = false,
    duration = 3.5,
    fadeDuration = 1.2,
    travelDistance = 190,
    maxVisible = 5,
    iconSize = 30,
    fontSize = 18,
    maxWidth = 480,
    rowSpacing = 1,
    scale = 1.0,
    anchor = {
        point = "CENTER",
        relativePoint = "CENTER",
        x = 0,
        y = 120,
    },
    debug = false,
}

ns.ValidationRanges = {
    minQuality = { min = 0, max = 5 },
    duration = { min = 0.5, max = 20.0 },
    fadeDuration = { min = 0.1, max = 5.0 },
    travelDistance = { min = 10, max = 500 },
    maxVisible = { min = 1, max = 20 },
    iconSize = { min = 12, max = 64 },
    fontSize = { min = 8, max = 32 },
    rowSpacing = { min = 0, max = 50 },
    scale = { min = 0.5, max = 3.0 },
    backgroundOpacity = { min = 0.0, max = 1.0 },
    rowOpacity = { min = 0.1, max = 1.0 },
    maxWidth = { min = 160, max = 800 },
}
